CREATE TABLE IF NOT EXISTS production_record_corrections (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  correction_type ENUM('packing','production') NOT NULL,
  production_batch_id BIGINT UNSIGNED NOT NULL,
  production_batch_output_id BIGINT UNSIGNED NOT NULL,
  packing_report_item_id BIGINT UNSIGNED NULL,
  original_quantity DECIMAL(14,3) NOT NULL,
  corrected_quantity DECIMAL(14,3) NOT NULL,
  original_batch_quantity DECIMAL(14,3) NULL,
  corrected_batch_quantity DECIMAL(14,3) NULL,
  inventory_delta DECIMAL(14,3) NOT NULL DEFAULT 0,
  raw_materials_adjusted TINYINT(1) NOT NULL DEFAULT 0,
  reason VARCHAR(500) NOT NULL,
  corrected_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_record_corrections_batch (production_batch_id, created_at),
  KEY idx_record_corrections_output (production_batch_output_id, created_at),
  KEY idx_record_corrections_packing (packing_report_item_id, created_at),
  CONSTRAINT fk_record_corrections_batch FOREIGN KEY (production_batch_id) REFERENCES production_batches (id),
  CONSTRAINT fk_record_corrections_output FOREIGN KEY (production_batch_output_id) REFERENCES production_batch_outputs (id),
  CONSTRAINT fk_record_corrections_packing FOREIGN KEY (packing_report_item_id) REFERENCES packing_report_items (id),
  CONSTRAINT fk_record_corrections_actor FOREIGN KEY (corrected_by) REFERENCES users (id),
  CONSTRAINT chk_record_corrections_reason CHECK (CHAR_LENGTH(TRIM(reason)) >= 5),
  CONSTRAINT chk_record_corrections_quantities CHECK (original_quantity >= 0 AND corrected_quantity >= 0)
) ENGINE=InnoDB;
