CREATE TABLE IF NOT EXISTS sales_return_commission_adjustments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  sales_return_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  sales_agent_user_id BIGINT UNSIGNED NOT NULL,
  treatment ENUM('no_effect','reduce','replace_base') NOT NULL,
  original_commission_base DECIMAL(14,2) NOT NULL,
  original_commission_amount DECIMAL(14,2) NOT NULL,
  adjusted_commission_base DECIMAL(14,2) NOT NULL,
  adjusted_commission_amount DECIMAL(14,2) NOT NULL,
  base_delta DECIMAL(14,2) NOT NULL DEFAULT 0,
  commission_delta DECIMAL(14,2) NOT NULL DEFAULT 0,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reversed_by BIGINT UNSIGNED NULL,
  reversed_at TIMESTAMP NULL,
  reversal_reason VARCHAR(500) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_return_commission_adjustment (sales_return_id),
  KEY idx_return_commission_order (order_id, created_at),
  KEY idx_return_commission_seller (sales_agent_user_id, created_at),
  CONSTRAINT fk_return_commission_sales_return FOREIGN KEY (sales_return_id) REFERENCES sales_returns (id),
  CONSTRAINT fk_return_commission_order FOREIGN KEY (order_id) REFERENCES orders (id),
  CONSTRAINT fk_return_commission_seller FOREIGN KEY (sales_agent_user_id) REFERENCES users (id),
  CONSTRAINT fk_return_commission_created_by FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT fk_return_commission_reversed_by FOREIGN KEY (reversed_by) REFERENCES users (id)
) ENGINE=InnoDB;
